#!/usr/bin/env bash
# Config, .env and compose files. Never the media: that is what your
# actual storage strategy is for.
#
# With an app name (update rollback): only that app's config dir.
# Scheduled / Back Up Now (no args): the full appliance snapshot.
#
# MediaCover and similar caches are regenerated by *arr apps on demand;
# including them made every update snapshot multi-gigabyte and look hung.
set -Eeuo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
load_env .env
app="${1:-}"
if [[ -n "$app" ]]; then
  case "$app" in
    *..*|*/*|*\\*) echo "invalid app name" >&2; exit 1 ;;
  esac
fi
stamp=$(date +%Y%m%d-%H%M%S)
suffix="${app:+-$app}"
out="${STACK_ROOT}/backups/kine-${stamp}${suffix}.tar.gz"
mkdir -p "${STACK_ROOT}/backups"
echo "Snapshotting config to ${out}..." >&2
excludes=(
  --exclude='*/logs/*'
  --exclude='*/cache/*'
  --exclude='*/transcoding-temp/*'
  --exclude='*/MediaCover/*'
  --exclude='*/Sentry/*'
  --exclude='*/asp/*'
)
# GNU tar exits 1 when a file changes while reading (common for live *arr DBs).
# That is a warning, not a failed backup — only treat exit >= 2 as fatal.
set +e
if [[ -n "$app" ]]; then
  tar czf "$out" "${excludes[@]}" -C "${STACK_ROOT}" "config/${app}"
else
  tar czf "$out" "${excludes[@]}" \
    -C "${STACK_ROOT}" config \
    -C "$(pwd)" .env docker-compose.yml compose catalogue.yml
fi
tar_rc=$?
set -e
if (( tar_rc >= 2 )); then
  echo "Snapshot failed (tar exit ${tar_rc})" >&2
  rm -f "$out"
  exit "$tar_rc"
fi
echo "Snapshot complete ($(du -h "$out" | cut -f1))." >&2
echo "$out"
# Keep the last 3 scheduled snapshots. Per-app update tarballs keep the
# newest one for this app; Helm also prunes other apps on the Snapshots page.
# `-r`/`--no-run-if-empty` is GNU-only; `rm -f` with no args is a no-op
# on BSD/macOS xargs too, so it's portable without the flag.
ls -1t "${STACK_ROOT}"/backups/kine-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9][0-9][0-9].tar.gz 2>/dev/null | tail -n +4 | xargs rm -f --
if [[ -n "$app" ]]; then
  ls -1t "${STACK_ROOT}"/backups/kine-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9][0-9][0-9]-"${app}".tar.gz 2>/dev/null | tail -n +2 | xargs rm -f --
fi
