#!/usr/bin/env bash
# Config, .env and compose files. Never the media: that is what your
# actual storage strategy is for.
#
# MediaCover and similar caches are regenerated by *arr apps on demand;
# including them made every update snapshot multi-gigabyte and look hung.
set -Eeuo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
load_env .env
stamp=$(date +%Y%m%d-%H%M%S)
out="${STACK_ROOT}/backups/kine-${stamp}.tar.gz"
mkdir -p "${STACK_ROOT}/backups"
echo "Snapshotting config to ${out}..." >&2
tar czf "$out" \
  --exclude='*/logs/*' \
  --exclude='*/cache/*' \
  --exclude='*/transcoding-temp/*' \
  --exclude='*/MediaCover/*' \
  --exclude='*/Sentry/*' \
  --exclude='*/asp/*' \
  -C "${STACK_ROOT}" config \
  -C "$(pwd)" .env docker-compose.yml compose catalogue.yml
echo "Snapshot complete ($(du -h "$out" | cut -f1))." >&2
echo "$out"
# Keep the last 10
# `-r`/`--no-run-if-empty` is GNU-only; `rm -f` with no args is a no-op
# on BSD/macOS xargs too, so it's portable without the flag.
ls -1t "${STACK_ROOT}"/backups/kine-*.tar.gz 2>/dev/null | tail -n +11 | xargs rm -f --
# Keep the last 10
# `-r`/`--no-run-if-empty` is GNU-only; `rm -f` with no args is a no-op
# on BSD/macOS xargs too, so it's portable without the flag.
ls -1t "${STACK_ROOT}"/backups/kine-*.tar.gz 2>/dev/null | tail -n +11 | xargs rm -f --
